spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shoppinglist
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

  data:
    rest:
      default-media-type: application/json

logging:
  file:
    name: logger.log
    clean-history-on-start: false
  level:
    root: warn
    com:
      shop: trace




my:
  secretkey: "secretkey"
  salt: "!/]}{ā"
